name: fori_feed
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.1.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  firebase_core: ^3.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rye
      fonts:
        - asset: assets/Rye-Regular.ttf



  assets:
    - assets/animations/news.json
